# azure-pipelines.yml
trigger:
  branches:
    include:
      - main   # adjust as per your branch

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  major: 1
  minor: 0

name: '$(major).$(minor).$(Rev:.r)'   # Version format: 1.0.1, 1.0.2, etc.

steps:

  # Step 2: Install .NET SDK
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '8.x'   # Change to your .NET version

  # Step 3: Restore dependencies
  - task: DotNetCoreCLI@2
    displayName: 'Restore dependencies'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  # Step 4: Build with version
  - task: DotNetCoreCLI@2
    displayName: 'Build solution with version'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  # Step 5: Run Tests
  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: 'test'
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build --verbosity normal'
    continueOnError: true

  # Step 6: Publish API
  - task: DotNetCoreCLI@2
    displayName: 'Publish API'
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true

  # Step 7: Publish Artifact
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

